### ISSUE TITLE
Spamming Notification Medium

### ISSUE THREAD

**Issue by parth995** [fivexl/terraform-aws-cloudtrail-to-slack#28]
Hey,
I guess while applying terraform code, there are multiple events for same resource in cloudtrail. Hence same bunch of messages get spammed/bombarded in notification channels like a noise. 
Would any workaround be suggested for the same please ?
Thanks

**Comment by Andrey9kin** [comment]
Hi @parth995! What kind of messages are those? If they are "access denied" type, then the best way is to tune up your access to include necessary permissions. If not, can you share an example?

**Comment by Andrey9kin** [comment]
The current best thinking - have a dynamodb with configurable TTL and store messages there (only ones that match the filter), use principal structure hash and action as a composite key, and store raw event, and ts of the slack message. if we get a new event that will match the composite key then use slack ts to send message as a reply in the thread instead of standalone message

**Comment by EreminAnton** [comment]
5854bcc
